---
- name: Configure RVM keys
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
- name: "Install RVM"
  shell: "curl -sSL https://get.rvm.io | bash -s stable"
  args:
    creates: /usr/local/rvm/bin/rvm
- name: "Install Ruby 2.1.4"
  shell: /usr/local/rvm/bin/rvm-shell -l -c "rvm install 2.1.4 --fuzzy"
  args:
    creates: /usr/local/rvm/rubies/ruby-2.1.4
- name: "Make 2.1.4 default"
  shell: /usr/local/rvm/bin/rvm-shell -l -c "rvm use 2.1.4 --default"
- name: "Install bundler"
  shell: /usr/local/rvm/bin/rvm-shell -l -c "gem install bundler"
