---
- name: install utility packages
  apt: name={{ item }} state=installed install_recommends=no update_cache=yes cache_valid_time=600
  with_items:
    - bzip2
    - figlet
    - graphviz
    - inotail
    - less
    - pv
    - reportbug
    - xz-utils
