---
- name: Packages config
  hosts: all
  # remote_user: root
  tasks:
    - include: tasks/sec.yml
    - include: tasks/util.yml
    - include: tasks/dev.yml

- name: sysstat
  hosts: all
  tasks:
    - name: ensure sysstat present
      apt: name=sysstat state=latest install_recommends=no
    - name: ensure sysstat enabled
      lineinfile: dest=/etc/default/sysstat state=present regexp="^ENABLED=" line='ENABLED="true"'

- name: PostgreSQL
  hosts: all
  tasks:
    - name: Install needed PostgreSQL packages and dev files
      apt: name={{ item }} state=latest install_recommends=no
      with_items:
        - postgresql-9.3
        - postgresql-client-9.3
        - postgresql-contrib-9.3
        - postgresql-server-dev-9.3
    - name: Enable PostgreSQL
      service: name=postgresql state=started enabled=yes

- name: Redis
  hosts: all
  tasks:
    - name: Install Redis
      apt: name=redis-server state=latest install_recommends=no
    - name: Enable Redis
      service: name=redis-server state=started enabled=yes
    - name: Install Redis Tools
      apt: name=redis-tools state=latest install_recommends=no

- name: RVM
  hosts: all
  tasks:
    - include: tasks/rvm.yml

- name: Install pycurl
  hosts: all
  gather_facts: no
  tasks:
    - name: Install pycurl
      apt: pkg=python-pycurl update_cache=yes cache_valid_time=600

- name: Essential services
  hosts: all
  tasks:
    - name: ensure ntpd is at the latest version
      apt: name=ntp state=latest
      notify:
        - restart ntpd
    - name: handle docker.io install
      apt: name=docker.io state=latest
  handlers:
    - name: restart ntpd
      service: name=ntp state=restarted

- name: MOTD
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure MOTD file has the right contents
      template: src=templates/motd.j2 dest=/etc/motd owner=root group=root mode=0644

- name: systemd stuff
  hosts: all
  tasks:
    - name: Ensure journald present
      apt: name=libsystemd-journal0 state=latest

- name: Vagrant user group config
  hosts: all
  tasks:
    - name: Add vagrant to groups
      user: name=vagrant groups=docker,rvm